# Generated by Django 3.2 on 2021-04-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investData', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intrisicdata',
            name='PercentageIncreament',
        ),
    ]
